# Generated by Django 5.2.4 on 2025-08-02 11:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='停车场名称')),
                ('address', models.CharField(max_length=200, verbose_name='停车场地址')),
                ('total_spaces', models.IntegerField(verbose_name='总车位数')),
                ('available_spaces', models.IntegerField(verbose_name='可用车位数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '停车场',
                'verbose_name_plural': '停车场管理',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='车牌号')),
                ('vehicle_type', models.CharField(max_length=50, verbose_name='车辆类型')),
                ('owner_name', models.CharField(max_length=100, verbose_name='车主姓名')),
                ('owner_phone', models.CharField(max_length=20, verbose_name='车主电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '车辆',
                'verbose_name_plural': '车辆管理',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='车位编号')),
                ('status', models.CharField(choices=[('available', '可用'), ('occupied', '已占用'), ('reserved', '已预约'), ('maintenance', '维护中')], default='available', max_length=20, verbose_name='状态')),
                ('is_handicapped', models.BooleanField(default=False, verbose_name='残疾人车位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='parking.parkinglot', verbose_name='所属停车场')),
            ],
            options={
                'verbose_name': '停车位',
                'verbose_name_plural': '停车位管理',
            },
        ),
        migrations.CreateModel(
            name='ParkingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='费用')),
                ('is_paid', models.BooleanField(default=False, verbose_name='是否已支付')),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_records', to='parking.parkingspace', verbose_name='停车位')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_records', to='parking.vehicle', verbose_name='车辆')),
            ],
            options={
                'verbose_name': '停车记录',
                'verbose_name_plural': '停车记录管理',
            },
        ),
    ]
