# Generated by Django 5.2.4 on 2025-08-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='停车场描述'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
    ]
