# Generated by Django 5.2.4 on 2025-08-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkinglot_description_parkinglot_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='available_spaces',
            field=models.IntegerField(default=0, verbose_name='可用车位数'),
        ),
    ]
