# Generated by Django 5.2.4 on 2025-08-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_parkinglot_available_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingrecord',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/', verbose_name='车辆照片'),
        ),
    ]
